<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Customer\Customer;
use Illuminate\Support\Facades\DB;

class CustomerSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $customers = [
            [
                'name' => "PT. PRIMATRANS NUSANTARA",
                'code' => "ID5879",
                'status' => "Active",
                'area' => "SERANG",
                'city' => "SERANG",
                'address1' => "Jl. Raya Meruya Utara No. 100, Kel. Meruya Utara, Jakarta Barat",
                'surat_menyurat_address' => "JL Raya  Cilegon KM 5 NO 28 Ds Drangong  Kec Taktakan",
                'join_date' => "2012-01-24",
                'no_pkd' => "063/PKD-PTPN/XI/2023",
                'account_group' => 'Export Market',
                'customer_class' => 'Gold',
                'term_of_payment' => 'CBD',
                'country' => 'Indonesia',
                'bank_garansi' => 'YA'
            ],
            [
                'name' => "CV. TRIJAYA PERKASA",
                'code' => "ID5282",
                'status' => "Active",
                'area' => "PONTIANAK",
                'city' => "PONTIANAK",
                'address1' => "Jl. Sungai Raya Dalam Gg. Ceria I B1-B2, RT 006 RW 001, Sungai Raya, Kubu Raya, Pontianak, Kalimantan Barat.",
                'surat_menyurat_address' => "JL. Trans Kalimantan Komp Pergudangan Prima LestariJ Jalur 3 Blok F No. 18",
                'join_date' => "2009-11-09",
                'no_pkd' => "055/PKD-CVTP/X/2023",
                'account_group' => 'Export Market',
                'customer_class' => 'Gold',
                'term_of_payment' => 'CBD',
                'country' => 'Indonesia',
                'bank_garansi' => 'YA'
            ],
            [
                'name' => "PT. MITRA SUBUR LESTARI TANGERANG",
                'code' => "ID5535",
                'status' => "Inactive",
                'area' => "TANGERANG",
                'city' => "TANGERANG",
                'address1' => "",
                'account_group' => 'Export Market',
                'customer_class' => 'Gold',
                'term_of_payment' => 'CBD',
                'country' => 'Indonesia',
                'bank_garansi' => 'TIDAK'
            ],
            [
                'name' => "PT. SARI PANGAN ABADI",
                'code' => "ID6345",
                'status' => "Active",
                'area' => "TANGERANG",
                'city' => "TANGERANG",
                'address1' => "Komplek Ruko Multiguna Duta Indah Iconic Panunggangan Utra Kota Tgr",
                'join_date' => "2021-07-21",
                'no_pkd' => "027/PKD-PTSPA/VI/2023",
                'account_group' => 'Export Market',
                'customer_class' => 'Gold',
                'term_of_payment' => 'CBD',
                'country' => 'Indonesia',
                'bank_garansi' => 'YA'
            ],
            [
                'name' => "PT. SINAR PARAMITA NIAGA",
                'code' => "ID5925",
                'status' => "Active",
                'area' => "LAMPUNG",
                'city' => "LAMPUNG",
                'address1' => "Jl. Padat Karya No. 9 Labuhan Dalam Kec Tanjung Senang Lampung",
                'join_date' => "2014-12-30",
                'no_pkd' => "016/PKD-PTSPN/V/2023",
                'account_group' => 'Export Market',
                'customer_class' => 'Gold',
                'term_of_payment' => 'CBD',
                'country' => 'Indonesia',
                'bank_garansi' => 'YA'
            ],
            [
                'name' => "PT. CITRA BHOGA JAYA",
                'code' => "ID3455",
                'status' => "Active",
                'area' => "BANDUNG",
                'city' => "BANDUNG",
                'address1' => "",
                'join_date' => "2010-07-26",
                'no_pkd' => "005/PKD-PTCBJ/I/2023",
                'account_group' => 'Export Market',
                'customer_class' => 'Gold',
                'term_of_payment' => 'CBD',
                'country' => 'Indonesia',
                'bank_garansi' => 'YA'
            ],
            [
                'name' => "PT. TRIBOGHA SENTOSA JAYA",
                'code' => "ID5880",
                'status' => "Active",
                'area' => "CIREBON, TASIKMALAYA",
                'city' => "CIREBON, TASIKMALAYA",
                'address1' => "",
                'join_date' => "2018-10-22",
                'no_pkd' => "053/PKD-PTTSJ/IX/2023",
                'account_group' => 'Export Market',
                'customer_class' => 'Gold',
                'term_of_payment' => 'CBD',
                'country' => 'Indonesia',
                'bank_garansi' => 'YA'
            ],
            [
                'name' => "PT. KARTIKA DISTRINDO",
                'code' => "ID5013",
                'status' => "Inactive",
                'area' => "JAKARTA & DEPOK",
                'city' => "JAKARTA & DEPOK",
                'address1' => "",
                'no_pkd' => "009/PKD-PTKD/III/2018",
                'account_group' => 'Export Market',
                'customer_class' => 'Gold',
                'term_of_payment' => 'CBD',
                'country' => 'Indonesia',
                'bank_garansi' => 'TIDAK'
            ],
            [
                'name' => "PT. DINAMIS ARTHA SUKSES",
                'code' => "ID6353",
                'status' => "Active",
                'area' => "JAKPUS & JAKTIM",
                'city' => "JAKPUS & JAKTIM",
                'address1' => "",
                'join_date' => "2022-02-15",
                'no_pkd' => "058/PKD-PTDAS/XI/2023",
                'account_group' => 'Export Market',
                'customer_class' => 'Gold',
                'term_of_payment' => 'CBD',
                'country' => 'Indonesia',
                'bank_garansi' => 'YA'
            ],
            [
                'name' => "PT. SARI INDO RASA",
                'code' => "ID6340",
                'status' => "Active",
                'area' => "JAKBAR & JAKUT",
                'city' => "JAKBAR & JAKUT",
                'address1' => "",
                'join_date' => "2021-02-01",
                'no_pkd' => "001/PKD-PTSIR/I/2024",
                'account_group' => 'Export Market',
                'customer_class' => 'Gold',
                'term_of_payment' => 'CBD',
                'country' => 'Indonesia',
                'bank_garansi' => 'YA'
            ],
            [
                'name' => "PT. PANGAN SEJAHTERA SANTOSA",
                'code' => "ID6392",
                'status' => "Active",
                'area' => "JAKSEL & DEPOK",
                'city' => "JAKSEL & DEPOK",
                'address1' => "",
                'join_date' => "2025-10-21",
                'no_pkd' => "069/PKD-PTPASS/X/2025",
                'account_group' => 'Export Market',
                'customer_class' => 'Gold',
                'term_of_payment' => 'CBD',
                'country' => 'Indonesia',
                'bank_garansi' => 'YA'
            ],
            [
                'name' => "PT. MITRA SUBUR LESTARI",
                'code' => "ID5918",
                'status' => "Active",
                'area' => "BOGOR",
                'city' => "BOGOR",
                'address1' => "",
                'join_date' => "2010-05-17",
                'no_pkd' => "017/PKD-PTMSL/V/2023",
                'account_group' => 'Export Market',
                'customer_class' => 'Gold',
                'term_of_payment' => 'CBD',
                'country' => 'Indonesia',
                'bank_garansi' => 'YA'
            ],
            [
                'name' => "PT. PRIMA MAKMUR LANGGENG PERKASA",
                'code' => "ID5878",
                'status' => "Active",
                'area' => "BEKASI",
                'city' => "BEKASI",
                'address1' => "",
                'join_date' => "2009-11-23",
                'no_pkd' => "060/PKD-PTPMLP/XI/2023",
                'account_group' => 'Export Market',
                'customer_class' => 'Gold',
                'term_of_payment' => 'CBD',
                'country' => 'Indonesia',
                'bank_garansi' => 'YA'
            ],
            [
                'name' => "CV. ARINDRA MANDIRI",
                'code' => "ID5922",
                'status' => "Active",
                'area' => "PALEMBANG",
                'city' => "PALEMBANG",
                'address1' => "",
                'join_date' => "2014-01-02",
                'no_pkd' => "064/PKD-CVAM/XII/2023",
                'account_group' => 'Export Market',
                'customer_class' => 'Gold',
                'term_of_payment' => 'CBD',
                'country' => 'Indonesia',
                'bank_garansi' => 'YA'
            ],
            [
                'name' => "PT. SINAR PARAMITA NIAGA",
                'code' => "ID4898",
                'status' => "Active",
                'area' => "BANGKA",
                'city' => "BANGKA",
                'address1' => "",
                'join_date' => "2014-12-30",
                'no_pkd' => "016/PKD-PTSPN/V/2023",
                'account_group' => 'Export Market',
                'customer_class' => 'Gold',
                'term_of_payment' => 'CBD',
                'country' => 'Indonesia',
                'bank_garansi' => 'YA'
            ],
            [
                'name' => "CV. SUMBER BERKAT ABADI",
                'code' => "ID6335",
                'status' => "Active",
                'area' => "JAMBI",
                'city' => "JAMBI",
                'address1' => "",
                'join_date' => "2020-07-29",
                'no_pkd' => "035/PKD-PTSBA/VII/2023",
                'account_group' => 'Export Market',
                'customer_class' => 'Gold',
                'term_of_payment' => 'CBD',
                'country' => 'Indonesia',
                'bank_garansi' => 'YA'
            ],
            [
                'name' => "CV. AROMA RAYA",
                'code' => "ID2026",
                'status' => "Inactive",
                'area' => "PADANG",
                'city' => "PADANG",
                'address1' => "",
                'join_date' => "2008-01-02",
                'no_pkd' => "034/PKD-CVAR/XI/2017",
                'account_group' => 'Export Market',
                'customer_class' => 'Gold',
                'term_of_payment' => 'CBD',
                'country' => 'Indonesia',
                'bank_garansi' => 'TIDAK'
            ],
            [
                'name' => "PT. KURNIA MAJU PERKASA",
                'code' => "ID6380",
                'status' => "Active",
                'area' => "PADANG",
                'city' => "PADANG",
                'address1' => "",
                'join_date' => "2025-02-05",
                'no_pkd' => "057/PKD-PTKMP/II/2025",
                'account_group' => 'Export Market',
                'customer_class' => 'Gold',
                'term_of_payment' => 'CBD',
                'country' => 'Indonesia',
                'bank_garansi' => 'YA'
            ],
            [
                'name' => "CV. ESSENINDO INTI CEMERLANG",
                'code' => "ID5014",
                'status' => "Inactive",
                'area' => "PEKANBARU",
                'city' => "PEKANBARU",
                'address1' => "",
                'no_pkd' => "033/PKD-CVEIC/XI/2017",
                'account_group' => 'Export Market',
                'customer_class' => 'Gold',
                'term_of_payment' => 'CBD',
                'country' => 'Indonesia',
                'bank_garansi' => 'TIDAK'
            ],
            [
                'name' => "PT. PAN BARUNA",
                'code' => "ID6341",
                'status' => "Active",
                'area' => "PEKANBARU",
                'city' => "PEKANBARU",
                'address1' => "",
                'join_date' => "2021-04-08",
                'no_pkd' => "020/PKD-PTPB/V/2023",
                'account_group' => 'Export Market',
                'customer_class' => 'Gold',
                'term_of_payment' => 'CBD',
                'country' => 'Indonesia',
                'bank_garansi' => 'YA'
            ],
            [
                'name' => "PT. STARTMARA PRATAMA",
                'code' => "ID2853",
                'status' => "Active",
                'area' => "BATAM",
                'city' => "BATAM",
                'address1' => "",
                'join_date' => "2012-10-29",
                'no_pkd' => "046/PKD-PTSP/VIII/2023",
                'account_group' => 'Export Market',
                'customer_class' => 'Gold',
                'term_of_payment' => 'CBD',
                'country' => 'Indonesia',
                'bank_garansi' => 'YA'
            ],
            [
                'name' => "PT. ANEKA MULTI AROMA",
                'code' => "ID2643",
                'status' => "Active",
                'area' => "MEDAN",
                'city' => "MEDAN",
                'address1' => "",
                'join_date' => "2008-01-02",
                'no_pkd' => "011/PKD-PTAMA/III/2023",
                'account_group' => 'Export Market',
                'customer_class' => 'Gold',
                'term_of_payment' => 'CBD',
                'country' => 'Indonesia',
                'bank_garansi' => 'YA'
            ],
            [
                'name' => "PT. ANUGERAH BERKAT KEKAL",
                'code' => "ID6332",
                'status' => "Active",
                'area' => "BANDA ACEH",
                'city' => "BANDA ACEH",
                'address1' => "",
                'join_date' => "2020-01-20",
                'no_pkd' => "010/PKD-PTABK/IV/2024",
                'account_group' => 'Export Market',
                'customer_class' => 'Gold',
                'term_of_payment' => 'CBD',
                'country' => 'Indonesia',
                'bank_garansi' => 'YA'
            ],
            [
                'name' => "CV. PERINDO",
                'code' => "ID6333",
                'status' => "Active",
                'area' => "NIAS",
                'city' => "NIAS",
                'address1' => "",
                'join_date' => "2020-01-20",
                'no_pkd' => "033/PKD-CVPRND/VI/2023",
                'account_group' => 'Export Market',
                'customer_class' => 'Gold',
                'term_of_payment' => 'CBD',
                'country' => 'Indonesia',
                'bank_garansi' => 'YA'
            ],
            [
                'name' => "PT. MAJU ARTHA JAYA",
                'code' => "ID5060",
                'status' => "Inactive",
                'area' => "PURWOKERTO",
                'city' => "PURWOKERTO",
                'address1' => "",
                'no_pkd' => "017/PKD-PTMAJ/III/2018",
                'account_group' => 'Export Market',
                'customer_class' => 'Gold',
                'term_of_payment' => 'CBD',
                'country' => 'Indonesia',
                'bank_garansi' => 'TIDAK'
            ],
            [
                'name' => "CV. CENTRA MAXIMA CITABOGA",
                'code' => "ID5401",
                'status' => "Active",
                'area' => "KUDUS",
                'city' => "KUDUS",
                'address1' => "",
                'join_date' => "2018-03-08",
                'no_pkd' => "024/PKD-PTCMC/III/2018",
                'account_group' => 'Export Market',
                'customer_class' => 'Gold',
                'term_of_payment' => 'CBD',
                'country' => 'Indonesia',
                'bank_garansi' => 'YA'
            ],
            [
                'name' => "CV. PAYUNG MAS SEJAHTERA-SMB",
                'code' => "ID5550",
                'status' => "Active",
                'area' => "SEMARANG BARAT",
                'city' => "SEMARANG BARAT",
                'address1' => "",
                'join_date' => "2017-12-04",
                'no_pkd' => "049/PKD-CVPMS/VIII/2023",
                'account_group' => 'Export Market',
                'customer_class' => 'Gold',
                'term_of_payment' => 'CBD',
                'country' => 'Indonesia',
                'bank_garansi' => 'YA'
            ],
            [
                'name' => "CV. PAYUNG MAS SEJAHTERA-SMT",
                'code' => "ID3110",
                'status' => "Active",
                'area' => "SEMARANG TIMUR",
                'city' => "SEMARANG TIMUR",
                'address1' => "",
                'join_date' => "2017-11-21",
                'no_pkd' => "048/PKD-CVPMS/VIII/2023",
                'account_group' => 'Export Market',
                'customer_class' => 'Gold',
                'term_of_payment' => 'CBD',
                'country' => 'Indonesia',
                'bank_garansi' => 'YA'
            ],
            [
                'name' => "PT. PRATAMA ABADI SANTOSO",
                'code' => "ID5100",
                'status' => "Active",
                'area' => "TEGAL",
                'city' => "TEGAL",
                'address1' => "",
                'join_date' => "2018-03-02",
                'no_pkd' => "014/PKD-PTPAS/V/2023",
                'account_group' => 'Export Market',
                'customer_class' => 'Gold',
                'term_of_payment' => 'CBD',
                'country' => 'Indonesia',
                'bank_garansi' => 'YA'
            ],
            [
                'name' => "UD. KARTIKA SEJAHTERA",
                'code' => "ID3350",
                'status' => "Inactive",
                'area' => "BOJONEGORO",
                'city' => "BOJONEGORO",
                'address1' => "",
                'join_date' => "2019-06-13",
                'no_pkd' => "038/PKD-UDKS/VII/2023",
                'account_group' => 'Export Market',
                'customer_class' => 'Gold',
                'term_of_payment' => 'CBD',
                'country' => 'Indonesia',
                'bank_garansi' => 'TIDAK'
            ],
            [
                'name' => "PT. TUJUH BERLIAN SAKTI",
                'code' => "ID6378",
                'status' => "Active",
                'area' => "BOJONEGORO",
                'city' => "BOJONEGORO",
                'address1' => "",
                'join_date' => "2024-08-22",
                'no_pkd' => "014/PKD-PTTBS/VIII/2024",
                'account_group' => 'Export Market',
                'customer_class' => 'Gold',
                'term_of_payment' => 'CBD',
                'country' => 'Indonesia',
                'bank_garansi' => 'YA'
            ],
            [
                'name' => "PT. ERICO INDONESIA, JEMBER",
                'code' => "ID4330",
                'status' => "Inactive",
                'area' => "JEMBER",
                'city' => "JEMBER",
                'address1' => "",
                'account_group' => 'Export Market',
                'customer_class' => 'Gold',
                'term_of_payment' => 'CBD',
                'country' => 'Indonesia',
                'bank_garansi' => 'TIDAK'
            ],
            [
                'name' => "PT. DISTRINDO AMAN SEJAHTERA, JEMBER",
                'code' => "-", // Missing ID in source
                'status' => "Inactive",
                'area' => "JEMBER",
                'city' => "JEMBER",
                'address1' => "",
                'account_group' => 'Export Market',
                'customer_class' => 'Gold',
                'term_of_payment' => 'CBD',
                'country' => 'Indonesia',
                'bank_garansi' => 'TIDAK'
            ],
            [
                'name' => "CV. LAJU JAYA MAKMUR-JEMBER",
                'code' => "ID6365",
                'status' => "Active",
                'area' => "JEMBER",
                'city' => "JEMBER",
                'address1' => "",
                'join_date' => "2023-07-31",
                'no_pkd' => "040/PKD-CVLJM/VII/2023",
                'account_group' => 'Export Market',
                'customer_class' => 'Gold',
                'term_of_payment' => 'CBD',
                'country' => 'Indonesia',
                'bank_garansi' => 'YA'
            ],
            [
                'name' => "CV. LAJU JAYA CEMERLANG",
                'code' => "ID7360",
                'status' => "Active",
                'area' => "MADURA",
                'city' => "MADURA",
                'address1' => "",
                'join_date' => "2019-06-12",
                'no_pkd' => "023/PKD-CVLJC/V/2023",
                'account_group' => 'Export Market',
                'customer_class' => 'Gold',
                'term_of_payment' => 'CBD',
                'country' => 'Indonesia',
                'bank_garansi' => 'YA'
            ],
            [
                'name' => "CV. ANUGERAH MEGAH SENTOSA",
                'code' => "ID6336",
                'status' => "Inactive",
                'area' => "MALANG",
                'city' => "MALANG",
                'address1' => "",
                'join_date' => "2022-11-07",
                'no_pkd' => "043/PKD-CVAMS/VIII/2023",
                'account_group' => 'Export Market',
                'customer_class' => 'Gold',
                'term_of_payment' => 'CBD',
                'country' => 'Indonesia',
                'bank_garansi' => 'TIDAK'
            ],
            [
                'name' => "PT. TUJUH BERLIAN SAKTI",
                'code' => "ID6389",
                'status' => "Active",
                'area' => "MALANG",
                'city' => "MALANG",
                'address1' => "Jl. Raya Narogong Km 11 Pangkalan 1B No 2, Bantar Gebang Bekasi",
                'join_date' => "2025-07-30",
                'no_pkd' => "014/PKD-PTTBS/VIII/2024",
                'account_group' => 'Export Market',
                'customer_class' => 'Gold',
                'term_of_payment' => 'CBD',
                'country' => 'Indonesia',
                'bank_garansi' => 'YA'
            ],
            [
                'name' => "PT. NARWASTU AGUNG SENTOSA",
                'code' => "ID5870",
                'status' => "Inactive",
                'area' => "SURABAYA",
                'city' => "SURABAYA",
                'address1' => "",
                'no_pkd' => "043/PKD-PTNAS/IX/2018",
                'account_group' => 'Export Market',
                'customer_class' => 'Gold',
                'term_of_payment' => 'CBD',
                'country' => 'Indonesia',
                'bank_garansi' => 'TIDAK'
            ],
            [
                'name' => "UD. HAPPY",
                'code' => "ID6349",
                'status' => "Inactive",
                'area' => "BANYUWANGI",
                'city' => "BANYUWANGI",
                'address1' => "",
                'account_group' => 'Export Market',
                'customer_class' => 'Gold',
                'term_of_payment' => 'CBD',
                'country' => 'Indonesia',
                'bank_garansi' => 'TIDAK'
            ],
            [
                'name' => "PT. DISTRINDO AMAN SEJAHTERA, BANYUWANGI",
                'code' => "ID3360",
                'status' => "Inactive",
                'area' => "BANYUWANGI",
                'city' => "BANYUWANGI",
                'address1' => "",
                'account_group' => 'Export Market',
                'customer_class' => 'Gold',
                'term_of_payment' => 'CBD',
                'country' => 'Indonesia',
                'bank_garansi' => 'TIDAK'
            ],
            [
                'name' => "CV. LAJU JAYA MAKMUR-BANYUWANGI",
                'code' => "ID6364",
                'status' => "Active",
                'area' => "BANYUWANGI",
                'city' => "BANYUWANGI",
                'address1' => "",
                'join_date' => "2023-07-31",
                'no_pkd' => "041/PKD-CVLJM/VII/2023",
                'account_group' => 'Export Market',
                'customer_class' => 'Gold',
                'term_of_payment' => 'CBD',
                'country' => 'Indonesia',
                'bank_garansi' => 'YA'
            ],
            [
                'name' => "CV. BOGA SWARNA TIMUR",
                'code' => "ID6352",
                'status' => "Active",
                'area' => "SIDOARJO & MOJOKERTO",
                'city' => "SIDOARJO & MOJOKERTO",
                'address1' => "",
                'join_date' => "2022-04-06",
                'no_pkd' => "050/PKD-CVBST/VIII/2023",
                'account_group' => 'Export Market',
                'customer_class' => 'Gold',
                'term_of_payment' => 'CBD',
                'country' => 'Indonesia',
                'bank_garansi' => 'YA'
            ],
            [
                'name' => "PT. ANEKA NIAGA",
                'code' => "ID5069",
                'status' => "Active",
                'area' => "KUPANG",
                'city' => "KUPANG",
                'address1' => "",
                'join_date' => "2010-05-17",
                'no_pkd' => "062/PKD-PTAN/XII/2023",
                'account_group' => 'Export Market',
                'customer_class' => 'Gold',
                'term_of_payment' => 'CBD',
                'country' => 'Indonesia',
                'bank_garansi' => 'YA'
            ],
            [
                'name' => "PT. SINAR MAYURI",
                'code' => "ID6338",
                'status' => "Active",
                'area' => "DENPASAR, BALI",
                'city' => "DENPASAR, BALI",
                'address1' => "",
                'join_date' => "2020-10-07",
                'no_pkd' => "042/PKD-PTSM/VIII/2023",
                'account_group' => 'Export Market',
                'customer_class' => 'Gold',
                'term_of_payment' => 'CBD',
                'country' => 'Indonesia',
                'bank_garansi' => 'YA'
            ],
            [
                'name' => "CV. SURYA PUTRA PERKASA",
                'code' => "ID6331",
                'status' => "Active",
                'area' => "LOMBOK",
                'city' => "LOMBOK",
                'address1' => "",
                'join_date' => "2019-12-19",
                'no_pkd' => "026/PKD-CVSPP/VI/2023",
                'account_group' => 'Export Market',
                'customer_class' => 'Gold',
                'term_of_payment' => 'CBD',
                'country' => 'Indonesia',
                'bank_garansi' => 'YA'
            ],
            [
                'name' => "PT MITRA USAHA FLORES",
                'code' => "ID6370",
                'status' => "Active",
                'area' => "FLORES, NTT",
                'city' => "FLORES, NTT",
                'address1' => "",
                'join_date' => "2023-11-10",
                'no_pkd' => "061/PKD-PTMUF/XI/2023",
                'account_group' => 'Export Market',
                'customer_class' => 'Gold',
                'term_of_payment' => 'CBD',
                'country' => 'Indonesia',
                'bank_garansi' => 'YA'
            ],
            [
                'name' => "CV AUSINDO DEWATA",
                'code' => "ID6369",
                'status' => "Inactive",
                'area' => "DENPASAR, BALI (HORECA)",
                'city' => "DENPASAR, BALI (HORECA)",
                'address1' => "",
                'join_date' => "2023-11-10",
                'no_pkd' => "060/PKD/CVAD/XI/2023",
                'account_group' => 'Export Market',
                'customer_class' => 'Gold',
                'term_of_payment' => 'CBD',
                'country' => 'Indonesia',
                'bank_garansi' => 'TIDAK'
            ],
            [
                'name' => "CV RESVILA",
                'code' => "ID6391",
                'status' => "Active",
                'area' => "DENPASAR, BALI (HORECA)",
                'city' => "DENPASAR, BALI (HORECA)",
                'address1' => "",
                'join_date' => "2025-08-25",
                'no_pkd' => "068/PKD-CVRSV/VIII/2025",
                'account_group' => 'Export Market',
                'customer_class' => 'Gold',
                'term_of_payment' => 'CBD',
                'country' => 'Indonesia',
                'bank_garansi' => 'YA'
            ],
            [
                'name' => "CV. PAYUNG MAS SEJAHTERA-SOLO",
                'code' => "ID3100",
                'status' => "Active",
                'area' => "SOLO",
                'city' => "SOLO",
                'address1' => "",
                'join_date' => "2017-12-04",
                'no_pkd' => "047/PKD-CVPMS/VIII/2023",
                'account_group' => 'Export Market',
                'customer_class' => 'Gold',
                'term_of_payment' => 'CBD',
                'country' => 'Indonesia',
                'bank_garansi' => 'YA'
            ],
            [
                'name' => "CV. TIRA PERSADA",
                'code' => "ID2536",
                'status' => "Active",
                'area' => "YOGYAKARTA",
                'city' => "YOGYAKARTA",
                'address1' => "",
                'join_date' => "2009-09-14",
                'no_pkd' => "030/PKD-CVTP/VI/2023",
                'account_group' => 'Export Market',
                'customer_class' => 'Gold',
                'term_of_payment' => 'CBD',
                'country' => 'Indonesia',
                'bank_garansi' => 'YA'
            ],
            [
                'name' => "CV. KINDO",
                'code' => "ID6357",
                'status' => "Active",
                'area' => "MAGELANG",
                'city' => "MAGELANG",
                'address1' => "",
                'join_date' => "2022-07-01",
                'no_pkd' => "022/PKD-CVKND/V/2023",
                'account_group' => 'Export Market',
                'customer_class' => 'Gold',
                'term_of_payment' => 'CBD',
                'country' => 'Indonesia',
                'bank_garansi' => 'YA'
            ],
            [
                'name' => "PT. ANUGERAH TRITUNGGAL DISTRINDO",
                'code' => "ID6354",
                'status' => "Active",
                'area' => "PURWOKERTO",
                'city' => "PURWOKERTO",
                'address1' => "",
                'join_date' => "2022-07-04",
                'no_pkd' => "003/PKD-PTATD/VII/2022",
                'account_group' => 'Export Market',
                'customer_class' => 'Gold',
                'term_of_payment' => 'CBD',
                'country' => 'Indonesia',
                'bank_garansi' => 'YA'
            ],
            [
                'name' => "CV. YASA BOGA",
                'code' => "ID5191",
                'status' => "Active",
                'area' => "TULUNG AGUNG",
                'city' => "TULUNG AGUNG",
                'address1' => "",
                'join_date' => "2009-11-03",
                'no_pkd' => "052/PKD-CVYB/IX/2023",
                'account_group' => 'Export Market',
                'customer_class' => 'Gold',
                'term_of_payment' => 'CBD',
                'country' => 'Indonesia',
                'bank_garansi' => 'YA'
            ],
            [
                'name' => "PT. ERICO INDONESIA, Madiun",
                'code' => "ID6330",
                'status' => "Inactive",
                'area' => "MADIUN",
                'city' => "MADIUN",
                'address1' => "",
                'account_group' => 'Export Market',
                'customer_class' => 'Gold',
                'term_of_payment' => 'CBD',
                'country' => 'Indonesia',
                'bank_garansi' => 'TIDAK'
            ],
            [
                'name' => "CV. ANUGERAH MEGAH SENTOSA",
                'code' => "ID6360",
                'status' => "Inactive",
                'area' => "MADIUN",
                'city' => "MADIUN",
                'address1' => "",
                'join_date' => "2022-11-07",
                'no_pkd' => "043/PKD-CVAMS/VIII/2023",
                'account_group' => 'Export Market',
                'customer_class' => 'Gold',
                'term_of_payment' => 'CBD',
                'country' => 'Indonesia',
                'bank_garansi' => 'TIDAK'
            ],
            [
                'name' => "UD. ILHAM SARI SEJAHTERA",
                'code' => "ID6390",
                'status' => "Active",
                'area' => "MADIUN",
                'city' => "MADIUN",
                'address1' => "Jl. Raya Taman Asri Kav. 49, Kel. Tambak Sumur, Kec. Waru, Sidoarjo, Jawa Timur.",
                'join_date' => "2025-08-01",
                'no_pkd' => "067/PKD-UDISS/VIII/2025",
                'account_group' => 'Export Market',
                'customer_class' => 'Gold',
                'term_of_payment' => 'CBD',
                'country' => 'Indonesia',
                'bank_garansi' => 'YA'
            ],
            [
                'name' => "CV. BERKAT USAHA",
                'code' => "ID5300",
                'status' => "Active",
                'area' => "TERNATE",
                'city' => "TERNATE",
                'address1' => "",
                'join_date' => "2018-07-16",
                'no_pkd' => "045/PKD-CVBU/VIII/2023",
                'account_group' => 'Export Market',
                'customer_class' => 'Gold',
                'term_of_payment' => 'CBD',
                'country' => 'Indonesia',
                'bank_garansi' => 'YA'
            ],
            [
                'name' => "PT. CIPTA LANGGENG MITRA SUKSES",
                'code' => "ID5350",
                'status' => "Active",
                'area' => "GORONTALO",
                'city' => "GORONTALO",
                'address1' => "",
                'join_date' => "2018-02-21",
                'no_pkd' => "008/PKD-PTCLP/IV/2023",
                'account_group' => 'Export Market',
                'customer_class' => 'Gold',
                'term_of_payment' => 'CBD',
                'country' => 'Indonesia',
                'bank_garansi' => 'YA'
            ],
            [
                'name' => "UD. MITRA KENCANA",
                'code' => "ID5920",
                'status' => "Active",
                'area' => "MANADO",
                'city' => "MANADO",
                'address1' => "",
                'join_date' => "2018-03-16",
                'no_pkd' => "007/PKD-UDMK/II/2024",
                'account_group' => 'Export Market',
                'customer_class' => 'Gold',
                'term_of_payment' => 'CBD',
                'country' => 'Indonesia',
                'bank_garansi' => 'YA'
            ],
            [
                'name' => "CV. MULTI MANDIRI",
                'code' => "ID2800",
                'status' => "Inactive",
                'area' => "MERAUKE",
                'city' => "MERAUKE",
                'address1' => "",
                'no_pkd' => "047/PKD-CVMM/IX/2018",
                'account_group' => 'Export Market',
                'customer_class' => 'Gold',
                'term_of_payment' => 'CBD',
                'country' => 'Indonesia',
                'bank_garansi' => 'TIDAK'
            ],
            [
                'name' => "PT MARIAT INTI KENCANA",
                'code' => "ID6373",
                'status' => "Active",
                'area' => "MERAUKE",
                'city' => "MERAUKE",
                'address1' => "Gudang Tugu Boto, Jl. Klodran Selatan, Ruko No. 2, Desa/Kelurahan Klodran, Kec. Colomadu, Kab. Karanganyar, Provinsi Jawa Tengah, Kode Pos: 57172",
                'join_date' => "2024-01-25",
                'no_pkd' => "004/PKD-PTMIK/I/2024",
                'account_group' => 'Export Market',
                'customer_class' => 'Gold',
                'term_of_payment' => 'CBD',
                'country' => 'Indonesia',
                'bank_garansi' => 'YA'
            ],
            [
                'name' => "CV. SETIA TUNGGAL",
                'code' => "ID5919",
                'status' => "Active",
                'area' => "JAYAPURA",
                'city' => "JAYAPURA",
                'address1' => "",
                'join_date' => "2013-02-20",
                'no_pkd' => "028/PKD-CVST/VI/2023",
                'account_group' => 'Export Market',
                'customer_class' => 'Gold',
                'term_of_payment' => 'CBD',
                'country' => 'Indonesia',
                'bank_garansi' => 'YA'
            ],
            [
                'name' => "PT. MARIAT INTI PERKASA",
                'code' => "ID6368",
                'status' => "Active",
                'area' => "TIMIKA",
                'city' => "TIMIKA",
                'address1' => "",
                'join_date' => "2019-05-20",
                'no_pkd' => "057/PKD-PTMIP/X/2023",
                'account_group' => 'Export Market',
                'customer_class' => 'Gold',
                'term_of_payment' => 'CBD',
                'country' => 'Indonesia',
                'bank_garansi' => 'YA'
            ],
            [
                'name' => "CV. ASTERA LESTARI",
                'code' => "ID6334",
                'status' => "Inactive",
                'area' => "SORONG",
                'city' => "SORONG",
                'address1' => "",
                'no_pkd' => "036/PKD-CVAL/VII/2023",
                'account_group' => 'Export Market',
                'customer_class' => 'Gold',
                'term_of_payment' => 'CBD',
                'country' => 'Indonesia',
                'bank_garansi' => 'TIDAK'
            ],
            [
                'name' => "CV. DELTA MANDIRI PERKASA",
                'code' => "ID6374",
                'status' => "Active",
                'area' => "SORONG",
                'city' => "SORONG",
                'address1' => "Jl. K.H. Mas Mansyur No. 162, Kel. Bendan Kergon, Kec. Pekalongan Barat, Pekalongan, Jawa Tengah.",
                'join_date' => "2024-05-17",
                'no_pkd' => "011/PKD-CVDMP/V/2024",
                'account_group' => 'Export Market',
                'customer_class' => 'Gold',
                'term_of_payment' => 'CBD',
                'country' => 'Indonesia',
                'bank_garansi' => 'YA'
            ],
            [
                'name' => "CV. JAYA MANDIRI",
                'code' => "ID6347",
                'status' => "Active",
                'area' => "MANOKWARI",
                'city' => "MANOKWARI",
                'address1' => "",
                'join_date' => "2021-07-12",
                'no_pkd' => "024/PKD-CVJM/V/2023",
                'account_group' => 'Export Market',
                'customer_class' => 'Gold',
                'term_of_payment' => 'CBD',
                'country' => 'Indonesia',
                'bank_garansi' => 'YA'
            ],
            [
                'name' => "CV. CAHAYA ANUGERAH ABADI",
                'code' => "ID5904",
                'status' => "Active",
                'area' => "PALU",
                'city' => "PALU",
                'address1' => "",
                'join_date' => "2016-09-28",
                'no_pkd' => "001/PKD-CVCAA/XII/2022",
                'account_group' => 'Export Market',
                'customer_class' => 'Gold',
                'term_of_payment' => 'CBD',
                'country' => 'Indonesia',
                'bank_garansi' => 'YA'
            ],
            [
                'name' => "PT. CAHAYA MAHAKAM SAMARINDA",
                'code' => "ID3370",
                'status' => "Active",
                'area' => "SAMARINDA",
                'city' => "SAMARINDA",
                'address1' => "",
                'join_date' => "2019-07-19",
                'no_pkd' => "010/PKD-PTCMS/III/2023",
                'account_group' => 'Export Market',
                'customer_class' => 'Gold',
                'term_of_payment' => 'CBD',
                'country' => 'Indonesia',
                'bank_garansi' => 'YA'
            ],
            [
                'name' => "CV. GEMILANG JAYA",
                'code' => "ID5921",
                'status' => "Active",
                'area' => "KENDARI",
                'city' => "KENDARI",
                'address1' => "",
                'join_date' => "2013-11-04",
                'no_pkd' => "002/PKD-CVGJ/XII/2022",
                'account_group' => 'Export Market',
                'customer_class' => 'Gold',
                'term_of_payment' => 'CBD',
                'country' => 'Indonesia',
                'bank_garansi' => 'YA'
            ],
            [
                'name' => "PT. NAM ANUGERAH MAKMUR",
                'code' => "ID5903",
                'status' => "Active",
                'area' => "AMBON",
                'city' => "AMBON",
                'address1' => "",
                'join_date' => "2012-07-25",
                'no_pkd' => "013/PKD-PTNAM/VI/2024",
                'account_group' => 'Export Market',
                'customer_class' => 'Gold',
                'term_of_payment' => 'CBD',
                'country' => 'Indonesia',
                'bank_garansi' => 'YA'
            ],
            [
                'name' => "PT. PINANG MAS BERSAUDARA",
                'code' => "ID5940",
                'status' => "Active",
                'area' => "BANJARMASIN",
                'city' => "BANJARMASIN",
                'address1' => "",
                'join_date' => "2018-02-21",
                'no_pkd' => "009/PKD-PTPMB/II/2023",
                'account_group' => 'Export Market',
                'customer_class' => 'Gold',
                'term_of_payment' => 'CBD',
                'country' => 'Indonesia',
                'bank_garansi' => 'YA'
            ],
            [
                'name' => "CV. SINAR GEMILANG",
                'code' => "ID5913",
                'status' => "Active",
                'area' => "MAKASSAR",
                'city' => "MAKASSAR",
                'address1' => "Jl. Lembeh No. 51, Kel. Melayu Baru, Kec. Wajo, Makassar, Sulawesi Selatan.",
                'surat_menyurat_address' => "Jl. Lembeh No. 51  Makasar Sulawesi Selatan",
                'join_date' => "2012-06-27",
                'no_pkd' => "054/PKD-PTTSJ/IX/2023",
                'account_group' => 'Export Market',
                'customer_class' => 'Gold',
                'term_of_payment' => 'CBD',
                'country' => 'Indonesia',
                'bank_garansi' => 'YA'
            ],
            [
                'name' => "CV. BINTANG BORNEO",
                'code' => "ID6337",
                'status' => "Active",
                'area' => "BALIKPAPAN",
                'city' => "BALIKPAPAN",
                'address1' => "Jl. MT. Haryono, Komp. Bukit Damai Blok C 1 No. 19 RT 035, Kel. Gunung Bahagia, Kec. Balikpapan Selatan, Balikpapan, Kalimantan Timur.",
                'surat_menyurat_address' => "Jl. MT Haryono  Komplek Bukit Damai Blok C 1 No 19  RT 035 Balikpapan",
                'join_date' => "2020-08-24",
                'no_pkd' => "037/PKD-CVBB/VIII/2023",
                'account_group' => 'Export Market',
                'customer_class' => 'Gold',
                'term_of_payment' => 'CBD',
                'country' => 'Indonesia',
                'bank_garansi' => 'YA'
            ],
            [
                'name' => "CV. SURYA MANDIRI X",
                'code' => "ID5600",
                'status' => "Active",
                'area' => "TARAKAN",
                'city' => "TARAKAN",
                'address1' => "Jl. Kusuma Bangsa RT 008, Kel. Gunung Lingkas, Kec. Tarakan Timur, Tarakan, Kalimantan Utara.",
                'surat_menyurat_address' => "JL. Kusuma Bangsa  RT 008  Kel Gunung Lingkas Tarakan",
                'join_date' => "2017-11-28",
                'no_pkd' => "034/PKD-CVSMX/VI/2023",
                'account_group' => 'Export Market',
                'customer_class' => 'Gold',
                'term_of_payment' => 'CBD',
                'country' => 'Indonesia',
                'bank_garansi' => 'YA'
            ],
            [
                'name' => "CV. ANEKA PANGAN MULTI NIAGA",
                'code' => "ID6355",
                'status' => "Inactive",
                'area' => "BAU BAU",
                'city' => "BAU BAU",
                'address1' => "",
                'join_date' => "2022-06-28",
                'no_pkd' => "056/PKD-CVAPMN/X/2023",
                'account_group' => 'Export Market',
                'customer_class' => 'Gold',
                'term_of_payment' => 'CBD',
                'country' => 'Indonesia',
                'bank_garansi' => 'TIDAK'
            ],
            [
                'name' => "CV. GEMILANG JAYA",
                'code' => "ID6388",
                'status' => "Active",
                'area' => "BAU BAU",
                'city' => "BAU BAU",
                'address1' => "Jl. By Pass Km. 6 No. 28, Kel. Begalung Nan XX, Kec. Lubuk Begalung, Padang, Sumatera Barat.",
                'join_date' => "2025-06-18",
                'no_pkd' => "002/PKD-CVGJ/XII/2022",
                'account_group' => 'Export Market',
                'customer_class' => 'Gold',
                'term_of_payment' => 'CBD',
                'country' => 'Indonesia',
                'bank_garansi' => 'YA'
            ],
            [
                'name' => "PT. PADI MAS PRIMA SEHATI",
                'code' => "ID6376",
                'status' => "Active",
                'area' => "PALANGKARAYA",
                'city' => "PALANGKARAYA",
                'address1' => "JL. Marsekal Surya Dharma No 28 RT 004 RW 004 Selapajang Jaya Neglasari Tangerang",
                'join_date' => "2024-05-17",
                'no_pkd' => "012/PKD-PTPMPS/V/2024",
                'account_group' => 'Export Market',
                'customer_class' => 'Gold',
                'term_of_payment' => 'CBD',
                'country' => 'Indonesia',
                'bank_garansi' => 'YA'
            ],
        ];

        foreach ($customers as $data) {
            Customer::create($data);
        }
    }
}